version: '2'

# From http://www.masterzendframework.com/docker-development-environment/

services:
  nginx:
      image: nginx:latest
      ports:
          - 8080:80
      volumes:
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      volumes_from:
          - php
  php:
      environment:
          - APIKEY
      build: ./docker/php/
      expose:
          - 9000
      volumes:
          - .:/var/www/html
